import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "/styles/Home.module.scss";
import { useRouter } from "next/router";
import Link from "next/link";
const Home: React.FC = () => {
  const router = useRouter();
  const route = (param) => {
    router.push(param);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/img/air_1.png"
          alt="Picture of the author"
          width={500}
          height={500}
        />
        <h1 className={styles.title}>Welcome to nextjs app</h1>
        <p className={styles.description}>
          let go userID with Link{" "}
          <Link href="/admin/user/abc">
            <a style={{ borderBottom: "1px solid black" }}>user heres &rarr;</a>
          </Link>
        </p>

        <div className={styles.grid}>
          <div onClick={() => route("HelloWorld")} className={styles.card}>
            <h2>HelloWord&rarr;</h2>
            <p>go to file hello world</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
export default Home;
